### ISSUE TITLE
Not all functions are supported

### ISSUE THREAD

**Issue by cscetbon** [prabushitha/gremlin-visualizer#11]
It seems some functions are not supported. For instance using `has('email', containing("test"))` does not work

**Comment by prabushitha** [comment]
Hi @cscetbon 
I've tested the given code and it works perfectly with tinkerpop server. Can you also check whether this method supports the tinkerpop based graph db which you are using?
![image](https://user-images.githubusercontent.com/7834419/80622096-f1b93c00-8a65-11ea-952b-cf30fa8bd177.png)

**Comment by cscetbon** [comment]
I'm surprised cause I used it with a Neptune DB and it doesn't. but querying it directly using python gives me a result.

**Comment by cscetbon** [comment]
@prabushitha nvm, I tried again and it worked. Maybe a connection issue at the time I tried it ...
Thanks
