### ISSUE TITLE
Am I doing right?

### ISSUE THREAD

**Issue by julio010101** [prabushitha/gremlin-visualizer#20]
Prabushitha,

Thank you for your project, it's very rare to find a visualization tool for Gremlin.

I did all the process but I can't see a sample graph, may be I'm doing something wrong. Please see below.

I've started a Gremlin Server followed by a Gremlin console. I've connected into the Server from the console:

> gremlin> :remote connect tinkerpop.server conf/remote.yaml session
> ==>Configured localhost/127.0.0.1:8182-[d3a7a1cb-2ba4-4c68-b93d-fd15ae3d8ade]
> 

After that I've created a sample graph as below:

> gremlin> graph = TinkerFactory.createModern()
> ==>tinkergraph[vertices:6 edges:6]
> gremlin> g = traversal().withEmbedded(graph)
> ==>graphtraversalsource[tinkergraph[vertices:6 edges:6], standard]

I can query the graph as below:

> gremlin> g.V()
> ==>v[1]
> ==>v[2]
> ==>v[3]
> ==>v[4]
> ==>v[5]
> ==>v[6]

I'm able to connect into the Gremlin Server from the Gremlin-Visualizer and run "g.V()" but nothing appears on the screen. I can see the command in the history too.

Best !
Julio

**Comment by prabushitha** [comment]
@julio010101 Hey, did you switch your **console** to the remote server?

1. connect to the server
```
:remote connect tinkerpop.server conf/remote.yaml
```
2. then switch the console
```
:remote console
```

3. create your graph
```
g.addV('Test')
```

After that try to execute commands in Gremlin-Visualizer

**Comment by julio010101** [comment]
Hello Prabushitha,

It worked fine!

Many thanks,

Best 

Julio
