### ISSUE TITLE
Invalid Host header when exposing the server to the outside

### ISSUE THREAD

**Issue by cscetbon** [prabushitha/gremlin-visualizer#7]
I'd like to use your frontend to access a database but I get an error when accessing the server remotely : 
```
Invalid Host header
```

Is there anything besides adding `disableHostCheck: true` to the proxy configuration ?

**Comment by prabushitha** [comment]
Did adding disableHostCheck: true solved the issue?

**Comment by cscetbon** [comment]
@prabushitha yes I had to. Without, even changing the hostname did not work. Thanks
