### ISSUE TITLE
Connect to Neptune over HTTPS via SSH port forwarding

### ISSUE THREAD

**Issue by CloudySnake** [prabushitha/gremlin-visualizer#8]
Not sure if you've seen this use case before. I have a new Neptune cluster in my test environment which by default forces connections over https not http.  I'm port forwarding via a bastion, so for manual queries from the command line I simply tell curl not to worry about the ssl hostname mismatch (localhost Vs the cert AWS is displaying).  Just wondering if anyone has gotten around this with the visualiser?  It's a fabulous tool.

**Comment by avnerlevy** [comment]
Same problem here. Regarding the certificate, you can add the Neptune cluster name to your local hosts file with 127.0.0.1. But I wasn't able to connect with this tool (container) either way. Does it use HTTP only?

**Comment by CloudySnake** [comment]
AWS changed their default setup a few months back, all new Neptune clusters are HTTPS/SSL only by default.  You can enable HTTP, but then you're lowering your security which isn't ideal.
I've not picked up the Neptune stuff for a while, but I have found a number of similar visualisation services that seem to work on HTTPS, might be worth looking at those too?
